IOTechSystems/iotech-c-utils

src/c/scheduler.c

Signed-off-by: Tom Fleming <tom@iotechsys.com>

ICU-2 stop now only stops when there is something to stop

---

src/c/logging.c

Signed-off-by: Iain Anderson <iain@iotechsys.com>

SDK-49 Log to file "-" means stdout

---

src/c/logging.c

Signed-off-by: Iain Anderson <iain@iotechsys.com>

SDK-49 dont fclose(stdout) if you want to get more output

---

include/iot/logger.h
src/c/logger.c

Also export log level names (useful for implementing custom loggers)

SDK-62 Allow loglevel setting

---

include/iot/base64.h
include/iot/data.h
src/c/CMakeLists.txt
src/c/base64.c
src/c/data.c
src/c/utests/data/data.c

Added base64 basic encoding and decoding, blob encoding to base64, two functions for string to blob conversion and corrected json encoding for character escaping.

XM-45 Added base64 encode/decode support

---

include/iot/threadpool.h
src/c/threadpool.c

Updated thread name to be based on both thread id in pool and pool id.

XM-100 Threadpool update to uniquely name threads from different pools

---

include/iot/data.h
src/c/data.c
src/c/utests/data/data.c

Signed-off-by: Edward Scott <edward.scott@iotechsys.com>

XRT-59 Added iot_data_vector_find

---

src/c/data.c
src/c/utests/data/data.c

Signed-off-by: Edward Scott <edward.scott@iotechsys.com>

XRT-78 Fix for JSON boolean value generation

---

scripts/Jenkinsfile
scripts/docker.sh

Updated image name to incorporate pid as pseudo random component.

XRT-79 Fix for duplicate docker image names

---

scripts/Dockerfile.centos-7
scripts/Dockerfile.centos-8
scripts/Dockerfile.fedora-30
scripts/Dockerfile.fedora-31
scripts/Jenkinsfile

Xrt 82 branch

---

src/c/data.c
src/c/utests/data/data.c

Also have updated precision of float/double encoding to match that of C device SDK.

XRT-219 Fix for converting max double in IOT data to json

---

include/iot/scheduler.h
scripts/Dockerfile.opensuse-15.2
scripts/Jenkinsfile
src/c/scheduler.c
src/c/thread.c
src/c/utests/data/data.c

FFT test update, plus addition of OpenSuse 15.2 build support (target for test). Plus fix for scheduler.

XRT-220 branch

---

include/iot/config.h
include/iot/container.h
src/c/config.c
src/c/utests/container/cont.c
src/c/utests/data/data.c

XRT-256 Additional component config check function added

---

include/iot/data.h
include/iot/scheduler.h
src/c/data.c
src/c/scheduler.c
src/c/utests/data/data.c
src/c/utests/scheduler/scheduler.c

* XRT-243: Added iot_schedule_reset
* XRT-243: Added iot_data_vector_resize

XRT-243: Add  iot_schedule_reset and iot_data_vector_resize

---

include/iot/data.h
src/c/data.c
src/c/utests/data/data.c

Signed-off-by: Iain Anderson <iain@iotechsys.com>

XRT-324 Add iot_data_[map,vector]_iter_replaceValue

---

include/iot/config.h
src/c/config.c
src/c/utests/data/data.c
src/c/utests/scheduler/scheduler.c

XRT-335 branch

---

RELEASE_NOTES.md
include/iot/data.h
src/c/data.c
src/c/iot.c
src/c/logger.c
src/c/utests/data/data.c

Data map remove functions added
Data cache cleanup moved to exit handler

XRT-429 branch

---

include/iot/json.h
src/c/data.c
src/c/json.c
src/c/utests/data/data.c

XRT-475 Process escape sequences in JSON strings

---

RELEASE_NOTES.md
include/iot/data.h
scripts/Dockerfile.alpine-3.11
scripts/Dockerfile.alpine-3.13
scripts/Jenkinsfile
scripts/docker.sh
scripts/linux.sh
scripts/package.sh
scripts/wrapper.sh
src/c/data.c
src/c/utests/data/data.c

Update to add Alpine 3.13 support, remove Alpine 3.11 support. 
Update to use native Alpine artifactory repository. 
Update to allow NULL to be passed to iot_data_equal.

XRT-506 branch

---

RELEASE_NOTES.md
include/iot/container.h
include/iot/iot.h
src/c/examples/container/container.c
src/c/examples/dynamic/dynamic.c
src/c/iot.c
src/c/tests/snippets/snippets.c
src/c/utests/misc/misc.c

Update for file write capability

XRT-564 branch

---

RELEASE_NOTES.md
include/iot/data.h
src/c/data.c
src/c/utests/data/data.c

Update to support null as a string config entry

XRT-615 branch

---

include/iot/os/linux.h
src/c/iot.c
src/c/logger.c

Closing PR for v1.1 branch #140 and created this PR for the fix on v1.2

XRT-594 Fix iot_file undefined on azure sphere with v1.2

---

scripts/Dockerfile.ubuntu-20.04
scripts/Jenkinsfile
scripts/auth.sh
scripts/docker.sh
scripts/linux.sh
sonar-project.properties
src/c/container.c
src/c/scheduler.c

XRT-651: SonarQube integration

---

README.md
RELEASE_NOTES.md
include/iot/data.h
include/iot/typecode.h
src/c/data.c
src/c/utests/data/data.c

Update to support Pointer data type. Plus merge of SonarQube integration.

XRT-699 branch

---

scripts/APKBUILD

Fixed header file copy to dev package only.

XRT-702 branch

---

RELEASE_NOTES.md
include/iot/logger.h
src/c/logger.c
src/c/utests/logger/logger.c

XRT-1135 branch

---

RELEASE_NOTES.md
include/iot/data.h
include/iot/logger.h
src/c/container.c
src/c/data.c
src/c/iot.c
src/c/logger.c
src/c/scheduler.c
src/c/utests/data/data.c
src/c/utests/logger/logger.c

Update to cache file and socket descriptors on private logger struct.
Fixes to work on AzureSphere.

XRT-1135 branch2

---

scripts/Dockerfile.azuresphere-11
scripts/Dockerfile.azuresphere-12
scripts/Jenkinsfile
src/c/data.c
src/c/scheduler.c
src/c/threadpool.c
src/c/time.c

Added support for latest SDK, plus removed some compiler warnings from the SDK.

XRT-1320 Support added for AzureSphere SDK 22.02 and API 12

---

RELEASE_NOTES.md
include/iot/data.h
src/c/data.c
src/c/utests/data/data.c

Data transform functions added

XRT-1336 branch

---

RELEASE_NOTES.md
include/iot/data.h
src/c/data.c
src/c/utests/data/data.c

Additional API updates to support multi-dimensional array handling

XRT-1336 branch5

---

RELEASE_NOTES.md
include/iot/data.h
include/iot/scheduler.h
scripts/Dockerfile.ubuntu-20.04
scripts/auth.sh
src/c/data.c
src/c/scheduler.c
src/c/utests/data/data.c
src/c/utests/scheduler/scheduler.c

Back port of scheduler optimisation onto 1.2 branch

XRT-1354 branch2

---

src/c/iot.c

XRT-1377 Fix for file write safety

---

src/c/utests/data/data.c

Had to create PR as 1.3 branch is write protected

XRT-1582: New unit test

---

src/c/utests/data/data.c

Can see it fails on ARM32: 
https://jenkins.iotechsys.com/job/IOT/job/XRT-1681-branch2/lastSuccessfulBuild/artifact/arm32/alpine-3.15/release/junit-Results.xml

XRT-1681: added new test for iot_data_from_json

---

RELEASE_NOTES.md
include/iot/data.h
src/c/data.c
src/c/utests/data/data.c

String to value range checking. Plus collection empty utility functions for list and map.

XRT-1686 branch

---

RELEASE_NOTES.md
include/iot/scheduler.h
src/c/data.c
src/c/scheduler.c
src/c/utests/scheduler/scheduler.c

Updated schedule reset function to support start delay

XRT-1840 branch

---

RELEASE_NOTES.md
include/iot/component.h
include/iot/data.h
src/c/component.c
src/c/data.c
src/c/examples/mycomponent/mycomponent.c
src/c/iot.c
src/c/logger.c
src/c/scheduler.c
src/c/threadpool.c

Update to support component categories. Plus fix for reading empty file.

XRT-1881 branch

---

RELEASE_NOTES.md
include/iot/data.h
src/c/data.c
src/c/scheduler.c
src/c/utests/data/data.c

Also fixed bug spotted in scheduler deletion

XRT-1897 List iterator remove function added

---

RELEASE_NOTES.md
include/iot/data.h
src/c/data.c
src/c/utests/data/data.c

Utility function to merge map contents

XRT-1997 Function added to merge maps

---

RELEASE_NOTES.md
include/iot/data.h
include/iot/scheduler.h
src/c/data.c
src/c/scheduler.c
src/c/utests/data/data.c
src/c/utests/scheduler/scheduler.c
src/c/uuid.c

Support added for string comparison function plus synchronous schedule execution
Fix added for compiling on MacOS

XRT-2109 Various updates

---

RELEASE_NOTES.md
include/iot/component.h
src/c/component.c
src/c/container.c
src/c/utests/container/cont.c

Feature required to support MQTT bridge component managing death notification

XRT-2183 core(sparkplug): Support added for container stopping callback

---

RELEASE_NOTES.md
include/iot/data.h
src/c/data.c
src/c/utests/data/data.c

Also added missing unit test for iot_data_map_get_list

XRT-2213 Function added to find an array in a map

---

RELEASE_NOTES.md
include/iot/data.h
src/c/data.c
src/c/utests/data/data.c

Function can be used to optimise binary data transforms.

XRT-2213 Function added to take buffer from binary and array data.

---

RELEASE_NOTES.md
include/iot/data.h
src/c/data.c
src/c/utests/data/data.c

Please let me know if I should back out formatting changes. I have updated my formatted to only reformat new code added for future

XRT-2302 feat(data): Added in iot_data_array_get function to get an element at a specific index

---

RELEASE_NOTES.md
include/iot/data.h
src/c/data.c
src/c/utests/data/data.c

Added functions to create additional integer constant data, plus function to return boolean from a map iterator. New functions required by Sparkplug XRT updates.

XRT-2156 Utility functions added

---

RELEASE_NOTES.md
include/iot/data.h
include/iot/logger.h
src/c/logger.c
src/c/utests/logger/logger.c

Also fixed reference counting with delegate, added a missing unit test and removed some API doc generation warnings.

XRT-2505 branch

---

RELEASE_NOTES.md
include/iot/file.h
include/iot/store.h
src/c/file.c
src/c/store.c
src/c/utests/misc/misc.c

Added function required for profile handling PR https://github.com/IOTechSystems/xrt/pull/1840
@SteveOss will I need to increase iot utils version here too?

XRT-2729: Add iot_store_config_list function

---

src/c/data.c

Use of spin lock removed (was broken)

Xrt 2798 branch
